import { dailySeed, weeklySeed } from "../lib/seedScenarios";
import { getDailyMeta, getWeeklyMeta } from "../lib/scenarioPriorities";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Generates supabase/seed.sql from the TypeScript fallback content + the
// priority map in lib/scenarioPriorities.ts. Run with `npm run gen:seed` after
// editing either file. Run the resulting seed.sql against production via
// psql or the Supabase SQL editor.

const lines: string[] = [
  "-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.",
  "-- Source: lib/seedScenarios.ts + lib/scenarioPriorities.ts.",
  "-- Re-run `npm run gen:seed` after edits.",
  "",
  "-- Idempotent: re-running this updates payload, scheduled_date, and iso_week",
  "-- on existing rows. Tier 1 scenarios carry a scheduled_date (daily) or",
  "-- iso_week (weekly); other rows null those fields so /today and /this-week",
  "-- fall through to hash rotation.",
  "",
];

function jsonbLiteral(value: unknown): string {
  const json = JSON.stringify(value);
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

function sqlText(s: string | null): string {
  if (s === null || s === "") return "null";
  return `'${s.replace(/'/g, "''")}'`;
}

for (const base of dailySeed) {
  const meta = getDailyMeta(base.id);
  const scheduled = meta.scheduled_date ?? null;
  const enriched = {
    ...base,
    scheduled_date: scheduled ?? "",
    priority: meta.priority,
    featured: meta.featured,
  };
  lines.push(
    `insert into scenarios (id, type, scheduled_date, iso_week, payload) values (`,
    `  '${base.id}',`,
    `  'daily',`,
    `  ${sqlText(scheduled)},`,
    `  null,`,
    `  ${jsonbLiteral(enriched)}`,
    `) on conflict (id) do update set payload = excluded.payload, type = excluded.type, scheduled_date = excluded.scheduled_date, iso_week = excluded.iso_week;`,
    "",
  );
}

for (const base of weeklySeed) {
  const meta = getWeeklyMeta(base.id);
  const week = meta.iso_week ?? null;
  const enriched = {
    ...base,
    iso_week: week ?? "",
    priority: meta.priority,
    featured: meta.featured,
  };
  lines.push(
    `insert into scenarios (id, type, scheduled_date, iso_week, payload) values (`,
    `  '${base.id}',`,
    `  'weekly',`,
    `  null,`,
    `  ${sqlText(week)},`,
    `  ${jsonbLiteral(enriched)}`,
    `) on conflict (id) do update set payload = excluded.payload, type = excluded.type, scheduled_date = excluded.scheduled_date, iso_week = excluded.iso_week;`,
    "",
  );
}

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${dailySeed.length} daily + ${weeklySeed.length} weekly scenarios to ${out}`);
