import { dailySeed, weeklySeed } from "../lib/seedScenarios";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Generates supabase/seed.sql from the TypeScript fallback content.
// Run with `npm run gen:seed` after editing lib/seedScenarios.ts.
// Run the resulting seed.sql in the Supabase SQL editor (or via the supabase CLI).

const lines: string[] = [
  "-- Generated by scripts/gen-seed-sql.ts — do not edit by hand.",
  "-- Source: lib/seedScenarios.ts. Re-run `npm run gen:seed` after edits.",
  "",
  "-- Idempotent: re-running this updates the payload of existing rows.",
  "",
];

function jsonbLiteral(value: unknown): string {
  const json = JSON.stringify(value);
  // Escape single quotes for SQL string literal.
  return `'${json.replace(/'/g, "''")}'::jsonb`;
}

for (const s of dailySeed) {
  lines.push(
    `insert into scenarios (id, type, payload) values (`,
    `  '${s.id}',`,
    `  'daily',`,
    `  ${jsonbLiteral(s)}`,
    `) on conflict (id) do update set payload = excluded.payload, type = excluded.type;`,
    "",
  );
}

for (const s of weeklySeed) {
  lines.push(
    `insert into scenarios (id, type, payload) values (`,
    `  '${s.id}',`,
    `  'weekly',`,
    `  ${jsonbLiteral(s)}`,
    `) on conflict (id) do update set payload = excluded.payload, type = excluded.type;`,
    "",
  );
}

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${dailySeed.length} daily + ${weeklySeed.length} weekly scenarios to ${out}`);
